### ISSUE TITLE
autoprefixer and less

### ISSUE THREAD

**Issue by wprater** [dbashford/mimosa-autoprefixer#2]
when I have these two modules installed, Im getting strange behavior.  If the output tree is clean, then the server won't start.  If it's already build some css output then the server will run, but the less files don't seem to be watched.

**Comment by dbashford** [comment]
Any chance you could put the barest of examples together for this and toss it on GH?

**Comment by wprater** [comment]
different issus, but probably same root cause.  you can just create a new project with mimosa with an express server, choose less, then add `autoprefixer` to the modules list.  try changing a less file to see the express server crash.

https://github.com/wprater/failing-mimosa-less-autoprefixer

**Comment by dbashford** [comment]
I get this, is it what you get?

```
path.js:313
        throw new TypeError('Arguments to path.resolve must be strings');
        ^
TypeError: Arguments to path.resolve must be strings
  at Object.exports.resolve (path.js:313:15)
  at Object.exports.relative (path.js:371:18)
  at MapGenerator.relative (/Users/dbashford/mimosaplay/test/node_modules/mimosa-autoprefixer/node_modules/autoprefixer/node_modules/postcss/lib/map-generator.js:165:19)
```

**Comment by wprater** [comment]
yeah. I have a fix. will do a PR tomorrow.

**Comment by dbashford** [comment]
Can you give the latest autoprefixer a try?

I didn't look too deep, but did notice that the version (of mimosa-autoprefixer) in NPM and the version on Github didn't match.  I've published this out and that problem disappeared.

**Comment by dbashford** [comment]
While I was there I tested out the latest autoprefixer and bumped it.

It does look like mimosa-less is having source map issues.

**Comment by dbashford** [comment]
Published a new version of mimosa-less as well.  Between the source map fix in that and the publish of the fix from here, should be good to go.  Let me know if things are still messed up?

**Comment by wprater** [comment]
your updates fixed the issue.  thanks!
